GET https://afternoon-sierra-18142.herokuapp.com/api/persons

###
GET https://afternoon-sierra-18142.herokuapp.com/info

###
GET https://afternoon-sierra-18142.herokuapp.com/api/persons/62eeb8ee58df0c0487905719

###
GET https://afternoon-sierra-18142.herokuapp.com/api/persons/666

###
GET https://afternoon-sierra-18142.herokuapp.com/api/persons/635282147aca1723dec7d331

###
DELETE https://afternoon-sierra-18142.herokuapp.com/api/persons/635282147aca1723dec7d331

###
POST https://afternoon-sierra-18142.herokuapp.com/api/persons
Content-Type: application/json

{}

###
POST https://afternoon-sierra-18142.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "foobar"
}

###
POST https://afternoon-sierra-18142.herokuapp.com/api/persons
Content-Type: application/json

{
    "number": 123
}

###
POST https://afternoon-sierra-18142.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "f",
    "number": 123
}

###
POST https://afternoon-sierra-18142.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "foobar2",
    "number": "102-334455"
}

###
PUT https://afternoon-sierra-18142.herokuapp.com/api/persons/635242ae220c04efa2792a0f
Content-Type: application/json

{
    "name": "foobar",
    "number": "111-222222"
}
