GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/62eeb8ee58df0c0487905719

###
GET http://localhost:3001/api/persons/666

###
GET http://localhost:3001/api/persons/6351936b3c440fff4b5d4812

###
DELETE http://localhost:3001/api/persons/6351936b3c440fff4b5d4812

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "foobar"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 123
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "foobar",
    "number": 123
}

###
PUT http://localhost:3001/api/persons/63519656de5dae1c38c39114
Content-Type: application/json

{
    "name": "foobar",
    "number": 321
}
