GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/63518828dfa5318f7b424a36

###
GET http://localhost:3001/api/persons/666

###
DELETE http://localhost:3001/api/persons/63518828dfa5318f7b424a36

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "foobar"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 123
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "foobar",
    "number": 123
}
