GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/62eeb8ee58df0c0487905719

###
GET http://localhost:3001/api/persons/666

###
GET http://localhost:3001/api/persons/6351936b3c440fff4b5d4812

###
DELETE http://localhost:3001/api/persons/6351936b3c440fff4b5d4812

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "foobar"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 123
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "f",
    "number": 123
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "foobar",
    "number": "102-334455"
}

###
PUT http://localhost:3001/api/persons/635242ae220c04efa2792a0f
Content-Type: application/json

{
    "name": "foobar",
    "number": "111-222222"
}
